[package]
name = "texplore"
version = "0.3.2"
edition.workspace = true
authors.workspace = true
description = "Terminal file explorer with git integration"

[dependencies]
chrono = "0.4"
crossterm = "0.28"
ignore = "0.4"
trash = "5.1"
